### ISSUE TITLE
'cassiopeia' has no attribute 'pp'

### ISSUE THREAD

**Issue by oligomyeggo** [YosefLab/Cassiopeia#109]
Hi @mattjones315, I am trying out the `preprocess.ipynb` [notebook](https://github.com/YosefLab/Cassiopeia/blob/refactor/notebooks/preprocess.ipynb) you mentioned in issue #79 from the `refactor` branch on some of my recently acquired GESTALT data. I am getting the following error: `AttributeError: module 'cassiopeia' has no attribute 'pp'` when trying to run any command that contains `cassiopeia.pp`. I'm not sure why; I was able to import cassiopeia no problem into my jupyter notebook (and as an installation check, I confirmed that running `reconstruct-lineage -h` in the command line gave me usage details). I remember when I first started using your tool back in March I was able to (mostly) run through the `process_fastq.ipynb` [notebook](https://github.com/YosefLab/Cassiopeia/blob/master/notebooks/process_fastq.ipynb) and cassiopeia was working fine. Was there a recent update to cassiopeia that would be throwing things off, or did I perhaps miss something in the install?

**Comment by mattjones315** [comment]
Hello,

Sorry you're running into trouble! It seems that your notebook (or python environment) is not detecting the new version of Cassiopeia. After you pulled from the `refactor` branch, did you reinstall? (You can do this with the simple `make install` command).

And then after reinstalling, can you verify that you're using the same python version and that the cassiopeia version you're importing is coming from the correct location that you installed it in?

**Comment by oligomyeggo** [comment]
That worked, thank you so much!
