### ISSUE TITLE
CassiopeiaTree character matrix has inconsistencies in the naming conventions

### ISSUE THREAD

**Issue by richardyz98** [YosefLab/Cassiopeia#112]
#106 
In the CassiopeiaTree, the character matrix attribute is called by `self._character_matrix` in some methods and in other methods called by `self.character_matrix`. 

Sorry I didn't catch this earlier!

**Comment by mattjones315** [comment]
Hi @richardyz98 -- this is actually intentional. The `self._character_matrix` is a hidden variable that stores the default character matrix. `self.character_matrix` is the property character matrix that can be set, copied, and manipulated. 

Is there another problem with this?
