### ISSUE TITLE
AttributeError calling cassiopeia.pp.align_sequences

### ISSUE THREAD

**Issue by oligomyeggo** [YosefLab/Cassiopeia#144]
Hi @mattjones315 and @Lioscro! I am running through your preprocessing pipeline with my GESTALT data, this time trying out the new global alignment option in `cassiopeia.pp.align_sequences` (thanks so much for including that!). Reading the API, it looks like for my GESTALT data that I should leave the `gap_open_penalty` and `gap_extend_penalty` as the default values (since those are what were originally used for the GESTALT technology) and set `method = "global"`. I did this and got the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-14-84b24ae4ce70> in <module>
      4 umi_table = cs.pp.align_sequences(umi_table, 
      5                                   ref_filepath = target_site_reference,
----> 6                                   method = "global")

~/.local/lib/python3.7/site-packages/ngs_tools/logging.py in inner(*args, **kwargs)
     60                 try:
     61                     self.namespace = namespace
---> 62                     return func(*args, **kwargs)
     63                 finally:
     64                     self.namespace = previous

~/Desktop/code/Cassiopeia/cassiopeia/preprocess/utilities.py in wrapper(*args, **kwargs)
     84     def wrapper(*args, **kwargs):
     85         logger.debug(f"Keyword arguments: {kwargs}")
---> 86         return wrapped(*args, **kwargs)
     87 
     88     return wrapper

~/Desktop/code/Cassiopeia/cassiopeia/preprocess/utilities.py in wrapper(*args, **kwargs)
     62         logger.info("Starting...")
     63         try:
---> 64             return wrapped(*args, **kwargs)
     65         finally:
     66             logger.info(f"Finished in {time.time() - t0} s.")

~/Desktop/code/Cassiopeia/cassiopeia/preprocess/pipeline.py in align_sequences(queries, ref_filepath, ref, gap_open_penalty, gap_extend_penalty, method, n_threads)
    528         )(
    529             delayed(align_partial)(ref, queries.loc[umi].seq)
--> 530             for umi in queries.index
    531         ),
    532     ):

~/.local/lib/python3.7/site-packages/ngs_tools/utils.py in __call__(self, *args, **kwargs)
    221     def __call__(self, *args, **kwargs):
    222         try:
--> 223             return Parallel.__call__(self, *args, **kwargs)
    224         finally:
    225             self._pbar.close()

~/.local/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1039             # remaining jobs.
   1040             self._iterating = False
-> 1041             if self.dispatch_one_batch(iterator):
   1042                 self._iterating = self._original_iterator is not None
   1043 

~/.local/lib/python3.7/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    857                 return False
    858             else:
--> 859                 self._dispatch(tasks)
    860                 return True
    861 

~/.local/lib/python3.7/site-packages/joblib/parallel.py in _dispatch(self, batch)
    775         with self._lock:
    776             job_idx = len(self._jobs)
--> 777             job = self._backend.apply_async(batch, callback=cb)
    778             # A job can complete so quickly than its callback is
    779             # called before we get here, causing self._jobs to

~/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py in apply_async(self, func, callback)
    206     def apply_async(self, func, callback=None):
    207         """Schedule a func to be run"""
--> 208         result = ImmediateResult(func)
    209         if callback:
    210             callback(result)

~/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py in __init__(self, batch)
    570         # Don't delay the application, to avoid keeping the input
    571         # arguments in memory
--> 572         self.results = batch()
    573 
    574     def get(self):

~/.local/lib/python3.7/site-packages/joblib/parallel.py in __call__(self)
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    262             return [func(*args, **kwargs)
--> 263                     for func, args, kwargs in self.items]
    264 
    265     def __reduce__(self):

~/.local/lib/python3.7/site-packages/joblib/parallel.py in <listcomp>(.0)
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    262             return [func(*args, **kwargs)
--> 263                     for func, args, kwargs in self.items]
    264 
    265     def __reduce__(self):

~/Desktop/code/Cassiopeia/cassiopeia/preprocess/alignment_utilities.py in align_global(ref, seq, substitution_matrix, gap_open_penalty, gap_extend_penalty)
     78     aln = aligner.align(ref, seq)
     79     return (
---> 80         ngs.sequence.alignment_to_cigar(aln.result_a, aln.result_b),
     81         aln.pos_b,
     82         aln.pos_a,

AttributeError: module 'ngs_tools.sequence' has no attribute 'alignment_to_cigar'
```

I just pulled the latest updates to the Master branch this morning, so I am not if it is perhaps an issue on my end with a package being out of date. Thanks so much for any help!

**Comment by Lioscro** [comment]
Hi, @oligomyeggo,
You might be using an older version of a library dependency for Cassiopeia.
I've noticed that sometimes `pip install` does not automatically update dependencies, for some reason.
Running `pip install ngs-tools --upgrade` should fix the issue.

**Comment by oligomyeggo** [comment]
Hi @Lioscro, thanks so much! That fixed it for me.

It looks like the global alignment strategy is working much better for my GESTALT data than the local alignment strategy did. With the local alignment strategy, I had ~20% missing data for cut site r9 and ~30% missing data for cute site r10 (out of 10 total cut sites). Using the global alignment strategy I had no missing data. Additionally, it looks like I was able to retain ~200-300 cells that were lost using the pipeline with the local alignment (though, I wonder if anything changed in `cs.pp.resolve_umi_sequence` code recently? When I ran through this pipeline initially using the local alignment, after running `cs.pp.resolve_umi_sequence` I got back 1996 cells, whereas now I am getting back 8770 cells. This shouldn't be affected by what alignment strategy I used downstream, so I am curious why I have so many more cells now at this point).

I've attached an image comparing vanilla greedy trees for my data set using the local alignment and global alignment strategies. To me it looks like the global alignment tree has a bit more structure to it than the local tree, which seems promising (there is still a large portion of the tree that is quite noisy; based on discussions with @mattjones315, for this experimental set up [15 embryos treated as 1], I would expect some amount of the tree to look noisy like this).

Besides altering the `cassiopeia.pp.align_sequences` call, I didn't change anything else from my previous run-through with the local alignment. I don't know if it's helpful, but I updated the config file that I provided in issue #110 and have attached that as well.

![local_vs_global](https://user-images.githubusercontent.com/13051802/130499713-e2bfe29b-f4ba-446d-8924-4829e2b17dbd.png)

[preprocess_gestalt_global.cfg.txt](https://github.com/YosefLab/Cassiopeia/files/7034248/preprocess_gestalt_global.cfg.txt)

**Comment by oligomyeggo** [comment]
Hi @Lioscro and @mattjones315, following up on this issue (as it relates to the global alignment). I was looking at the allele information for two cells that had identical barcodes according to the allele heatmap. I was curious about the colors. I noticed several areas in my allele heatmap where cells had the same color for several cut sites (see example image). When I went to look at a pair of cells that, according to the heatmap, shared 9/10 indels, I noticed that several of the indels seem to be duplicates of each other. Here is an example from my data (my apologies, but these cells do not correspond to the example image):

**Cell 1**
r1: CATCG[42:78D]GAGTC	
r2: CATCG[42:78D]GAGTC	
r3: CATCG[42:78D]GAGTC	
r4: CATCG[42:78D]GAGTC	
r5: ATCGA[151:1I]AGTATG	
r6: AGTCG[172:35D]ATGGA	
r7: AGTCG[172:35D]ATGGA	
r8: TGCTG[None]TCATG	
r9: AGTCG[243:27D]CGAGC
r10: AGCGA[None]CTATG	

**Cell 2**
r1: CATCG[42:78D]GAGTC	
r2: CATCG[42:78D]GAGTC	
r3: CATCG[42:78D]GAGTC	
r4: CATCG[42:78D]GAGTC	
r5: ATCGA[None]GTATG	
r6: TCGAC[164:54D]AGCAG	
r7: TCGAC[164:54D]AGCAG	
r8: TGCTG[None]TCATG	
r9: AGTCG[243:27D]CGAGC
r10: AGCGA[None]CTATG	

My understanding here is that there was 78 bp long deletion starting at base 42 in my barcode sequence [42:78D]. This makes sense when I compare the indel info with my barcode array, since that deletion starts in cut site 1, deletes the entirety of cut site 2 and 3, and most of cut site 4, and so that is why cut sites r1-r4 have the same indel info (since the deletion spans all four cut sites). Is this correct? And then because each cut site is getting the same indel, they are colored the same on the heatmap and so if I see a cell that has the same color repeated over multiple cut sites I should interpret that as one big deletion (like in the example image)?

I am curious why in this example Cell 1 and Cell 2 have a different starting sequence at cut site 6 and 7. This might require more digging on my end because, whereas the other indels here all start with the expected sequence contained in the cut sites before the cut position, the r6 and r7 indels do not. It looks like it is cutting somewhere other than the cut position.

![Screen Shot 2021-08-24 at 10 09 08 AM](https://user-images.githubusercontent.com/13051802/130669238-0c0185fb-5827-40f6-b062-0c152a5145a2.png)

**Comment by mattjones315** [comment]
Hi @oligomyeggo ,

So sorry for the delay in our response -- between vacations and miscellaneous deadlines we haven't been able to give the issues enough attention.

In any event, your understanding is exactly correct! This is how we decided to encode multi-site deletions. You could argue that another way is better but at least you understand what you're looking at here.

Let us know how else we can help!

Best,
Matt

**Comment by oligomyeggo** [comment]
Hi @mattjones315, totally not an issue at all!! There is no rush on my end. :) And thanks for getting back to me! Glad to know that I am interpreting things correctly. Seems like things are in pretty good shape on my end so far as processing our GESTALT data, and we are talking about doing future experiments that are optimized based on what we learned this iteration. I might open up one more issue in the near-ish future; I want to make sure that I am understanding how your `parse_cigar` and `call_alleles` functions are working because going through my data I am not quite sure why I am seeing such variation in sequence on either side of the cut sites in my alleles (and can't figure out where some allele sequences are coming from based on the overall sequences). Things are probably working as intended, I just want to understand how they're working. It's the last conceptual piece of the puzzle for me.

Thanks so much again for all of your help!
