### ISSUE TITLE
Command line tools not found

### ISSUE THREAD

**Issue by ShouWenWang** [YosefLab/Cassiopeia#155]
Hi! I followed the installation instructions, and the `make test` runs successfully. While I can run the command `cassiopeia-preprocess --help`, I could run `reconstruct-lineage --help`.  Any suggestions?

Here is my script for installation

```bash
conda create -n lineage_tree python=3.6 --yes
conda activate lineage_tree
pip install pytest
conda install cython --yes
make install
pip install --user ipykernel
python -m ipykernel install --user --name=lineage_tree
```

**Comment by mattjones315** [comment]
Hi Shou-Wen,

I'm glad you could get Cassiopeia to install and pass all the tests! In the newest version, we have deprecated the command line tools for tree reconstruction. Instead, we have developed a complete python-based API for reconstruction of trees which you can learn more about with this [tutorial](https://cassiopeia-lineage.readthedocs.io/en/latest/notebooks/reconstruct.html) on our documentation website. We have implemented several algorithms in addition to our Cassiopeia algorithms, which you can read more about [here](https://cassiopeia-lineage.readthedocs.io/en/latest/api/solver.html).

Regarding the preprocessing, you may proceed with the command line option using `cassiopeia-preprocess`, or you can use the python API which is detailed on this [preprocessing tutorial](https://cassiopeia-lineage.readthedocs.io/en/latest/notebooks/preprocess.html).

Please let us know if you run into any additional trouble and how we may assist! 

Thanks,
Matt

**Comment by ShouWenWang** [comment]
Thanks for the clarification. Super useful.
It would be useful then to update (or deprecate)
reconstruct_lineage_tutorial.pdf
<https://github.com/YosefLab/Cassiopeia/blob/master/reconstruct_lineage_tutorial.pdf>,
as it is outdated.

Also, during my installation, I find it necessary to cython first (and
pytest), which is not specified in the tutorial for installation.




*   BestShou-Wen Wang*

**Comment by mattjones315** [comment]
Hi Shou-Wen,

That's great advice, I'll make that change to our stable release. Thanks for using Cassiopeia and please do let us know if you would find anything else useful.

Best,
Matt
