### ISSUE TITLE
Missing  ~/.itolconfig

### ISSUE THREAD

**Issue by ShouWenWang** [YosefLab/Cassiopeia#156]
Hi, it would be really useful if you could provide an example iTol config file ~/.itolconfig, so that we know how to make our own file!

**Comment by mattjones315** [comment]
That's a great idea! I've added an example config file as `data/itolconfig_example` in the home directory with commit `ce94d59`.

**Comment by ShouWenWang** [comment]
This is awesome! However, I wonder what the api_key would be like, is it a password + username?  How can I get such an API key myself?

**Comment by mattjones315** [comment]
Hi Shou-Wen,

You will have to make an account on [iTOL](https://itol.embl.de/pricing.cgi), and once you do you should have access to an API key which is 22 character alphanumeric random code. You'll be able to access it from your user-account page on iTOL once you have made the account.

Hope this helps and let me know if you have any additional questions!

Best,
Matt

**Comment by ShouWenWang** [comment]
This is awesome! Thanks for the fast response!




*   BestShou-Wen Wang*

**Comment by ShouWenWang** [comment]
Hi, regarding to iTOL, I think this provides nice plot, but unfortunately
it requires subscription to use the API key.  Do you have any workaround?
Or some (free) alternative to visualize the tree in the package?




*   BestShou-Wen Wang*

**Comment by mattjones315** [comment]
Hi Shou-Wen,

There indeed is a free option to use iTOL without an API key -- you have unlimited access to the web portal, as far as I understand, though this requires a bit more manual work. Check out the "Upload" tab on the top bar on the home page of iTOL. I will say that the subscription is quite approachable (~$95 annually) so if you will use this service often, I think it's worth it. It's definitely been useful for us.

Alternatively, we have been thinking of implementing some basic functionality using either `ete3` or `ggtree` for plotting. These require a bit of work -- at least on our end, getting a the backend visualization for ete3 set up correctly has been difficult, and `ggtree` requires portability between R and python. These types of features are important for sure, but have taken the back seat as we implement more solving and analysis modules, which we think are currently more important. 

That being said, we're always hopeful that others in the community with time on their hands would consider contributing additional modules to Cassiopeia - the plotting module would be a great place to start, for example.

Thanks and please let me know if there are other things I can help out with.
