### ISSUE TITLE
Target site reference fasta in the Science article "Single-cell lineages reveal the rates, routes, and drivers of metastasis in cancer xenografts"

### ISSUE THREAD

**Issue by weipingz** [YosefLab/Cassiopeia#165]
Hi! I want to know whether the target site reference fasta in the Science article "Single-cell lineages reveal the rates, routes, and drivers of metastasis in cancer xenografts" is the same as the file "PCT48.ref.fasta" in the data directory or not. Looking forward to your reply. Thank you very much.

**Comment by mattjones315** [comment]
Dear @weipingz ,

Yes, that is the reference FASTQ that was used in that study. Please let me know if you have additional questions.

Best,
Matt
