### ISSUE TITLE
Installation instructions in readme

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/Cassiopeia#171]
https://github.com/YosefLab/Cassiopeia/blob/4a4ba1ac5bac1158f8ebc652ab7850c05ff95d59/README.md?plain=1#L34

This isn't required and you can't install python from pip?!

**Comment by mattjones315** [comment]
Whoops! Must have been a typo from a previous set of instructions. Fixed with commit 64d0449d61d6e90a744fb40a21a486502666e125
