### ISSUE TITLE
ERROR in align

### ISSUE THREAD

**Issue by cxyzju** [YosefLab/Cassiopeia#186]
Hello,
I was following the tutorial for the preprocessing, and when I get to the "align" step, I get an error thrown.
`IndexError: list index out of range`

Looking forward to your answers!
Best,
xinyi

**Comment by mattjones315** [comment]
Hi Xinyi,

I would like to help but you must give me more information about how you
are running the "align" step: for example, how are you invoking the
function; what data are you feeding into the align step, etc.

Thank you and hope to help.

Best,
Matt
