### ISSUE TITLE
How many intBCs are in the  intbc_whitelist?

### ISSUE THREAD

**Issue by lamyankin** [YosefLab/Cassiopeia#191]
Hi,
When I ran the [error_correct_intbcs_to_whitelist], 6 intBCs were used in the intbc_whitelist and got error. Generally, how many intBCs are in the intbc_whitelist? How could i get the  intbc_whitelist in the paper _Single-cell lineages reveal the rates, routes, and drivers of metastasis in cancer xenografts_
Looking forward to your reply

**Comment by mattjones315** [comment]
Hi @lamyankin ,

I think there is a misunderstanding about what the `error_correct_intbcs_to_whitelist` functionality is supposed to do. This is built for the express case where you know _exactly_ the intBCs that should appear in your dataset should be (realistically, a set of ~10-20 intBCs). In this case, this procedure will correct all intBCs to this set. This can be useful if you have an engineered mouse (for example, from our KP-Tracer work) where we have previously genotyped the intBCs in the mouse.

In the Quinn et al study that you cited, we do not have _a priori_ knowledge of the intBC sets and thus we do not error correct intBCs to the whitelist. If this case matches your setup, I suggest you turn off this error correction step.

You can read more about this in our tutorial [here](https://cassiopeia-lineage.readthedocs.io/en/latest/notebooks/preprocess.html#error_correct_intbcs_to_whitelist). 

Let me know if this answers your question or if I can be of any further assistance.

Thanks,
Matt

**Comment by lamyankin** [comment]
Yes！Thank you for your patience explanation. Now I had a clear understanding about it.
