### ISSUE TITLE
Esquires about data availability   

### ISSUE THREAD

**Issue by DHGK** [YosefLab/Cassiopeia#2]
Hello,

Congratulations on your publication! I’m so impressed by the article and was hoping to use the gastrulation compendium data as a reference for my study.

I used the accession number GSE122187 and got all 10x data. Although you have provided CellStates file and CellStatesKernel file, I'm wondering if you guys could share a metadata file included the cell-by-cell annotation you used in the paper?

Really appreciate all your help!

**Comment by yuqiyuqitan** [comment]
May I also send in a request of the cell type annotation metadata associated with your paper too?

Thank you very much!
Yuqi
