### ISSUE TITLE
 Regular scRNA-seq data as only input for Cassiopeia

### ISSUE THREAD

**Issue by ioyarzun** [YosefLab/Cassiopeia#206]
Hi there Cassiopeia Team!

I might be interested on using your tool for lineage tracing on a scRNA-seq dataset I am working with. However, this dataset has no CRISPR-Cas9 preprocessing of the cells and it is being difficult to figure on the documentation whether it is mandatory this CRISPR-Cas9 methodology to use the tool or not. So my question is, could I use regular/simple scRNA-seq data as input for your tool?

Thank you for time!
Iñigo.

**Comment by mattjones315** [comment]
Hi @ioyarzun ,

Thank you for this inquiry. To make sure I understand what you are asking about - do you have any sort of lineage-tracing technology in your system? Specifically, are you working with a dataset that was traced using a different effector from Cas9 (e.g., base editor or prime editing), or are you curious about performing pseudotemporal lineage tracing (like Monocle, for example) with Cassiopeia?

If it is the former - you are using a synthetic lineage tracer with a different effector - I think Cassiopeia will be suitable for your analysis. However, if you are hoping to infer the pseudotemporal ordering of cells from scRNAseq alone, Cassiopeia will not be useful unfortunately. If it is the latter, you might also want to check out [CoSpar](https://cospar.readthedocs.io/en/latest/) for your analysis.

Thanks for posting here, and hope this is helpful.

-Matt
