### ISSUE TITLE
Check whether the ILP Solver is using Gurobi

### ISSUE THREAD

**Issue by Marius1311** [YosefLab/Cassiopeia#218]
Hi there, quick question, how can I check whether the ILP solver is correctly using Gurobi? Or is this a stupid question, and the solver is always using gurobi under the hood, so as long as I get no error, things are fine? 

I got a bit confused when looking at the API because I realized that the `ILPSolver` has methods `generate_steiner_model` and `solve_steiner_instance`, which explicitly mention Gurobi in their description, while the `solve` method does not.

**Comment by mattjones315** [comment]
Hi @Marius1311,

Thanks for the question! There is no "backup" optimizer, so if the ILPSolver is running correctly then Gurobi is being used.

That's a good point on documentation - we will clarify this in the general `solve` docstring.

Let me know if you have other questions relating to whether or not Gurobi is installed correctly. If so, feel free to reopen this issue and we can continue the discussion.

-Matt
