### ISSUE TITLE
how to display cutsite name  in cas.pl.plot_matplotlib

### ISSUE THREAD

**Issue by tenlives** [YosefLab/Cassiopeia#222]
Hi, 
![image](https://github.com/YosefLab/Cassiopeia/assets/44781595/52e986eb-03a9-4421-ac74-5262014e6dc5)
When I  use cas.pl.plot_matplotlib function, I want to know which cutsite represent the color bar.
May I get some methods from you to display the cutsite?

Thanks!

**Comment by mattjones315** [comment]
Hi @tenlives,

Thanks for posting this question. Unfortunately we currently do not have a way of displaying the cutsite names in `cas.pl.plot_matplotlib`.

One hacky way to get this ordering though is if you were to create an indel lineage profile as so:

```
lineage_profile = cas.preprocess.utilities.convert_alleletable_to_lineage_profile(allele_table)
```

The ordering of the displayed intBCs will mirror the columns of that lineage profile. I hope this helps, and we will make a note to work on adding this functionality in a future release.
