### ISSUE TITLE
simulation data availability

### ISSUE THREAD

**Issue by shangguandong1996** [YosefLab/Cassiopeia#28]
Hi, Dear Developer
First, I want to thanks for your tool and shared code :).
And I am wondering whether you can offer some simulation data link, like the `test_possorted_genome_bam.bam` in  process_fastq.ipynb. After all, CellRange is time consuming. I believe some prepared data may help people to get acquainted faster.
```
## first specify the home directory, and possorted genome bam
home_dir = "."
genome_bam = "data/test_possorted_genome_bam.bam"
```

And I have another question about test_possorted_genome_bam.bam. It looks like this bam is the result of CellRange, but I found in the paper method, there is another step between `Assigning cell barcode and UMIs to each read` and `Aligning to the target site reference`.
> Finding the consensus sequence for each UMI. To potentially increase the speed of consensussequence finding, we attempt to trim reads to the same length for each UMI.

But I do not found this step in the Cassiopeia.
Please forgive me If I misunderstand something :)

Best wishes
Guandong Shang

**Comment by mattjones315** [comment]
Hello Guandong,

We have made all raw sequencing reads and processed allele tables (the output of the Cassiopeia pre-processing pipeline) available on GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146712). Unfortunately, the .bam files that you're referring to are quite large so we can't share them on github, and the admins at GEO do not allow .bam deposits. Running CellRanger on the raw sequencing reads on a cluster shouldn't take more than a day, if I recall correctly. 

Indeed, the .bam you're referring to is the result of CellRanger. The processing pipeline performs several steps which you can find in our example notebook (Cassiopeia/notebook/process_fastq.ipynb).

In addition, you can find simulated trees to test our reconstructions on at our Zenodo repository: https://zenodo.org/record/3706351#.X7M7HhNKgkg.

Hope this helps.

**Comment by shangguandong1996** [comment]
Thanks for your reply, Matt :) 
I just found you published a paper about Cassiopeia. Maybe I can see it first.

Best wishes
Guandong Shang
