### ISSUE TITLE
Sequencing module

### ISSUE THREAD

**Issue by yosefmai** [YosefLab/Cassiopeia#4]
Trying to run process_fastq.ipynb, I get an error regarding the Sequencing module:

```python
ModuleNotFoundError: No module named 'cassiopeia.ProcessingPipeline.process.sequencing'
```

It seems like this module is loaded in cassiopeia/ProcessingPipeline/process/collapseUMIReadsByMSALargeFile.py from a local directory:

```python
sys.path.append("/home/jah/projects/sequencing/code")
```
Could you please point me to where I can access / install that module?

**Comment by mattjones315** [comment]
Hello, 

Apologies for the late response here, and thank you for finding this error. The Sequencing library was removed a bit ago in favor of a pip-installable library called `hits`, which should automatically be installed with Cassiopeia (it's a dependency listed in our `setup.py`).  

The presence of the line importing the sequencing module in `process_fastq.ipynb` is no longer needed and in fact causes an error, as you saw. This was my mistake keeping it there and it is now removed. Removing that line from your python notebook should fix this issue. 

Apologies again for the late response and the error in the notebook import statements. Please let me know if you have any other questions! 

-Matt
