### ISSUE TITLE
Conversion to newick in the reconstruct_lineages notebook

### ISSUE THREAD

**Issue by aaronmck** [YosefLab/Cassiopeia#5]
I was just trying out some examples, and in the 'Post-Process Tree & Add Redundant Leaves' section, the command: 

```
g.newick = data_pipeline.convert_network_to_newick_format(g)
```

Gives me a 

```
'TypeError: 'Cassiopeia_Tree' object is not iterable' error. 
```

Looking at the tree class, it seems class function get_newick(self) calls this same function with the network, not the full object. Is the example notebook out of date? Thanks!

**Comment by mattjones315** [comment]
Hi Aaron,

Thanks for reaching out here and testing out Cassiopeia!

Unfortunately, yes, that notebook is out of date - apologies for misleading
you and certainly other users here. I believe you can fix this issue by
passing g.network to data_pipeline.convert_network_to_newick_format.

We are in the midst of merging much of our latest code into Cassiopeia (you
can find the latest developments on the staging branch) so I apologize for
some out-of-date tutorials - I'll go in today and try to fix some of the
tutorials I know are out of date. In the meantime, I hope that the fix
above will be helpful!

Thanks again and please let me know if there is anything else I can help
with!

-Matt Jones

**Comment by aaronmck** [comment]
No worries, if you're ahead of this I'll just close the issues. Thanks!

**Comment by jinyongfan** [comment]
Hi Matt, 
I am also confused how to transfer the cassiopeia tree object to newick file. When I used the cas.data.to_newick(cas_tree), 'TypeError: 'Cassiopeia_Tree' object is not iterable' error.  the same error as Aaron's. How to make it work?

**Comment by Counts-Xin** [comment]
> cas.data.to_newick(cas_tree)



> Hi Matt, I am also confused how to transfer the cassiopeia tree object to newick file. When I used the cas.data.to_newick(cas_tree), 'TypeError: 'Cassiopeia_Tree' object is not iterable' error. the same error as Aaron's. How to make it work?

Have you solved this problem?
