### ISSUE TITLE
Cassiopeia for time-point data

### ISSUE THREAD

**Issue by shikhagupta68** [YosefLab/Cassiopeia#7]
Hello, 
I wonder whether Cassiopeia pipeline can be used for scRNAseq data obtained at different time points during the process of cancer transformation? Please let me know.

Thank you,
Shikha

**Comment by mattjones315** [comment]
Hello Shikha,

Unfortunately this was the intent of the method and I’m not sure if it
could accommodate this use case trivially. Is this lineage tracing data?
Please provide a bit more background on the data types and intended outputs
and I can provide more insight.

Thanks,
Matt
