### ISSUE TITLE
PCT48 hardcoded into processing pipeline?

### ISSUE THREAD

**Issue by oligomyeggo** [YosefLab/Cassiopeia#79]
Hello! Thanks for creating this great tool to process data from single cell lineage tracing experiments. I am going through the `process_fastq.ipynb` notebook with my own example data (from Raj et al. 2020's scGESTALT paper). Things seemed to be working well until I hit the `process.call_indels` step, which returned an output .sam file that contained a header but was otherwise blank (i.e., no called indels for each sequence). Digging into this a little more, it looks like the input .sam file (generated from `process.align_sequences`) is not valid. The reference listed in the `@SQ` line is `PCT48.ref`, which is the reference used in the `process_fastq.ipynb` notebook. However, the alignments all show alignments to the `dsRed` reference, which is what I was using for my example data. This seems to be hardcoded in the `pipeline_utils.py` script (see [line 18](https://github.com/YosefLab/Cassiopeia/blob/d0f974abcbab4d41a71df781f127b8d00eb86328/cassiopeia/ProcessingPipeline/process/pipeline_utils.py#L18) and [line 210](https://github.com/YosefLab/Cassiopeia/blob/d0f974abcbab4d41a71df781f127b8d00eb86328/cassiopeia/ProcessingPipeline/process/pipeline_utils.py#L210)). I am wondering if there is some issue with the `PCT48.ref` being hardcoded that is causing the `process.call_indels` step to fail on my end with different example data?

I've included the following files from my example run: 1) sw_aligned.sam (output .sam file from `process.align_sequences`), 2) DsRed.fa (FASTA reference sequence), and 3) umi_table.sam (output .sam file from `process.call_indels`).
[gestalt_ex.zip](https://github.com/YosefLab/Cassiopeia/files/6152819/gestalt_ex.zip)

Versions:
Python 3.7.4
Emboss 6.6.0.0
Gurobi 9.1.1
Mac OS 10.15.7

I don't see any version numbers for Cassiopeia, but I just finished downloading and installing Cassiopeia yesterday so I should be working with the most current versions of everything.

Thank you for any help or insight!

**Comment by mattjones315** [comment]
Hello Caitlin,

Thank you for reaching out and trying Cassiopeia for your data! The version of Cassiopeia in the master branch, unfortunately, is specifically equipped to preprocess data from our lineage tracer (published in Chan et al, 2019). However, with character matrices in hand (which you can create from the GESTALT technology), you should definitely be able to reconstruct lineages.

The good news is that we anticipated this issue some time ago, and have integrated it into our large software refactor, accessible from the `refactor` branch. In this refactoring, we have made the preprocessing pipeline much more flexible. Specifically, at the step that you are stuck on -- the aligning step and indel calling step -- we have allowed users to specify their own references as well as TargetSite design (i.e. where to look for cuts, etc.). We haven't hosted our documentation yet, unfortunately, but the code is very well documented and hopefully would offer enough to get you started with this code if you're interested. You can find an updated notebook on this branch called `preprocess.ipynb`. 

I hope this will be useful for you, and please let us know how else we can help!

**Comment by oligomyeggo** [comment]
Hi Matt,

Sorry for the delay! I will look into the `refactor` branch and check out the corresponding `preprocess.ipynb` notebook, and reach back out if I come across any other sticking points/questions. Thank you for your help! I appreciate it.

**Comment by mattjones315** [comment]
Closing this thread because it's now being discussed in #109 and #110
